# -*- coding: utf-8 -*-
"""Train_HVCN_LoRA_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdKczPuAvuAOrQ5bAsooerKuLkG8tf8v
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

!pip install -q git+https://github.com/bmaltais/kohya_ss.git
!pip install -q bitsandbytes accelerate transformers safetensors ftfy